In [1]:
import sys
sys.path.append('../../Python_scripts')

## Import packages
from config import *
from support import *
from cosmo_support import *
import csv_to_latex as to_latex

/home/zhuge/miniconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
data=pd.read_csv('../../Data/FRB_new.csv')
print(data.columns)
data.head()

Index(['FRB', 'z', 'gl', 'gb', 'DM', 'DM_ext(ne2001)', 'DM_ext(ymw16)',
       'Ref.'],
      dtype='object')

,FRB,z,gl,gb,DM,DM_ext(ne2001),DM_ext(ymw16),Ref.
0,FRB 20180814A,0.06800,136.460000,16.580000,190.900,73.07,52.49,https://www.nature.com/articles/s41586-018-0864-x
1,FRB 20181030A,0.00385,133.400000,40.900000,103.396,33.05,41.15,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20220529A,0.18390,130.787670,-41.858020,246.000,176.05,185.08,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01600,8.839200,-70.185700,1458.150,1397.19,1414.57,https://www.cambridge.org/core/journals/public...
4,FRB 20220717A,0.36295,19.835158,-17.632032,637.340,489.01,524.12,https://arxiv.org/pdf/2407.02173

In [3]:
import re
def frb_sort_key(frb_str):
    match = re.search(r'FRB\s*(\d+)([A-Z]+)', frb_str)
    if match:
        number = int(match.group(1))
        letter = match.group(2)
        return (number, letter)
    return (0, 'Z')
data_sorted = data.sort_values('FRB', key=lambda x: x.apply(frb_sort_key)).reset_index(drop=True)
data_sorted.head()

,FRB,z,gl,gb,DM,DM_ext(ne2001),DM_ext(ymw16),Ref.
0,FRB 20121102A,0.19273,174.890,-0.230,557.0,338.58,239.93,https://iopscience.iop.org/article/10.1088/000...
1,FRB 20171020A,0.00860,29.300,-51.300,114.1,45.73,58.26,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20180301A,0.33040,204.412,-6.481,522.0,341.27,239.44,https://iopscience.iop.org/article/10.3847/153...
3,FRB 20180814A,0.06800,136.460,16.580,190.9,73.07,52.49,https://www.nature.com/articles/s41586-018-0864-x
4,FRB 20180916B,0.03370,129.710,3.730,349.3,120.39,-5.52,https://iopscience.iop.org/article/10.3847/204...

In [4]:
""" data_sorted=data_sorted[['FRB', 'z','gl', 'gb','DM', 'DM_ext(ne2001)', 'DM_ext(ymw16)', 'Ref']]
data_sorted.head() """

" data_sorted=data_sorted[['FRB', 'z','gl', 'gb','DM', 'DM_ext(ne2001)', 'DM_ext(ymw16)', 'Ref']]\ndata_sorted.head() "

In [5]:
citation_dict={
    'https://iopscience.iop.org/article/10.1088/0004-637X/790/2/101': 'Spitler_2014', # FRB 121102
    'https://www.nature.com/articles/s41586-018-0864-x': '2019Nature_CHIME',
    'https://iopscience.iop.org/article/10.3847/2041-8213/ab4a80':'Andersen_2019',
    'https://arxiv.org/abs/2503.04727': '2025arXiv_YeLi',
    'https://www.cambridge.org/core/journals/publications-of-the-astronomical-society-of-australia/article/commensal-realtime-askap-fast-transient-incoherentsum-survey/3486D8F81134D00A43DACFAC9831FAA4':'2025ASKAP',
    'https://arxiv.org/pdf/2407.02173':'2024MNRAS_2trb_sys',
    'https://www.nature.com/articles/s41586-018-0588-y':'2018Nature171020',
    'https://academic.oup.com/mnras/article/486/3/3636/5432360?login=false':'2019MNRAS_180301',
    'https://www.science.org/doi/10.1126/science.aaw5903':'2019Science180924',
    'https://www.science.org/doi/10.1126/science.aay0073':'2019Science181112',
    'CHIME4':'Bhardwaj_2024',
    'CHIME_host':'Ibik_2024',
    'CHIME13':'Michilli_2023',
    'https://www.nature.com/articles/s41586-022-04755-5':'2022Nature_CHNiu',
    'https://www.nature.com/articles/s41586-019-1389-7':'2019Nature_Ravi',
    'https://iopscience.iop.org/article/10.3847/1538-4357/aba4ac':'Law_2020',
    'https://iopscience.iop.org/article/10.3847/1538-3881/ac3aec':'Bhandari_2022',
    'https://academic.oup.com/mnras/article/514/2/1961/6595347?login=false':'2022MNRAS_Rajwade',
    'https://ui.adsabs.harvard.edu/abs/2022MNRAS.513..982R/abstract':'2022MNRAS_Ravi',
    'https://iopscience.iop.org/article/10.3847/1538-4357/acc178':'Bhandari_2023',
    'https://arxiv.org/abs/2302.05465':'2023ApJ_Garden',
    '20210405I':'2024MNRAS20210405I',
    'https://www.wis-tns.org/object/frb20210410d':'2023MNRAS.524.2064C',
    'https://arxiv.org/abs/2307.09502':'2024NatAs...8.1429C',
    'https://iopscience.iop.org/article/10.3847/2041-8213/abeaa6':'Bhardwaj_2021',
    'https://arxiv.org/pdf/2502.11217':'2025arXiv_CHIME_localized',
    'https://arxiv.org/pdf/2409.16952':'Sharma1',
    'https://iopscience.iop.org/article/10.3847/2041-8213/aae7cb':'Mahony_2018',
    'https://data.caltech.edu/records/z80e7-7wk68':'2025AJ_Ravi',
    'https://www.astronomerstelegram.org/?read=15679':'2023ApJ_20220912A',
    'https://www.wis-tns.org/object/frb20230526a':'2025ASKAP',
    'https://www.astronomerstelegram.org/?read=16420':'2024ApJ_20240114A',
    'https://www.wis-tns.org/object/FRB20240229A/discovery-cert':'Sharma1',
    'Macquart':'2020Nature_Macquart'
}

In [6]:
data_sorted['Ref.'] = data_sorted['Ref.'].replace(citation_dict)
data_sorted['Ref.']=r'\citet{'+data_sorted['Ref.']+'}'
data_sorted.head()

,FRB,z,gl,gb,DM,DM_ext(ne2001),DM_ext(ymw16),Ref.
0,FRB 20121102A,0.19273,174.890,-0.230,557.0,338.58,239.93,\citet{Spitler_2014}
1,FRB 20171020A,0.00860,29.300,-51.300,114.1,45.73,58.26,\citet{Mahony_2018}
2,FRB 20180301A,0.33040,204.412,-6.481,522.0,341.27,239.44,\citet{Bhandari_2022}
3,FRB 20180814A,0.06800,136.460,16.580,190.9,73.07,52.49,\citet{2019Nature_CHIME}
4,FRB 20180916B,0.03370,129.710,3.730,349.3,120.39,-5.52,\citet{Andersen_2019}

In [7]:
head2=r'& & (deg) & (deg) & $ (\rm pc \, cm^{-3})$ & $(\rm pc \, cm^{-3})$ & $(\rm pc \, cm^{-3})$ & '
to_latex.dataframe_to_latex_long(data_sorted,'./table.tex',caption='Well localized FRB samples',label='tab:data',head2=head2)

LaTeX already save to: ./table.tex

'\\startlongtable\n\\begin{deluxetable}{cccccccc}\n\\label{tab:data}\n\\centering\n\\tablecaption{Well localized FRB samples}\n\\tablehead{\\colhead{FRB} & \\colhead{z} & \\colhead{gl} & \\colhead{gb} & \\colhead{DM} & \\colhead{$\\DM_{ext}$(ne2001)} & \\colhead{$\\DM_{ext}$(ymw16)} & \\colhead{Ref.} \\\\\n& & (deg) & (deg) & $ (\\rm pc \\, cm^{-3})$ & $(\\rm pc \\, cm^{-3})$ & $(\\rm pc \\, cm^{-3})$ & \n}\n\\startdata\nFRB 20121102A & 0.19273 & 174.89 & -0.23 & 557.0 & 338.58 & 239.93 & \\citet{Spitler_2014} \\\\\nFRB 20171020A & 0.0086 & 29.3 & -51.3 & 114.1 & 45.73 & 58.26 & \\citet{Mahony_2018} \\\\\nFRB 20180301A & 0.3304 & 204.412 & -6.481 & 522.0 & 341.27 & 239.44 & \\citet{Bhandari_2022} \\\\\nFRB 20180814A & 0.068 & 136.46 & 16.58 & 190.9 & 73.07 & 52.49 & \\citet{2019Nature_CHIME} \\\\\nFRB 20180916B & 0.0337 & 129.71 & 3.73 & 349.3 & 120.39 & -5.52 & \\citet{Andersen_2019} \\\\\nFRB 20180924B & 0.3214 & 0.7424 & -49.4147 & 361.42 & 290.92 & 303.77 & \\citet{2019Science180924} \\\\\nFRB 20181030A & 0.00385 & 133.4 & 40.9 & 103.396 & 33.05 & 41.15 & \\citet{Andersen_2019} \\\\\nFRB 20181112A & 0.4755 & 342.5995 & -47.6988 & 589.27 & 517.55 & 530.24 & \\citet{2019Science181112} \\\\\nFRB 20181220A & 0.02746 & 105.24 & -10.73 & 209.4 & 53.55 & 57.27 & \\citet{Bhardwaj_2024} \\\\\nFRB 20181223C & 0.03024 & 207.75 & 79.51 & 112.5 & 62.57 & 63.35 & \\citet{Bhardwaj_2024} \\\\\nFRB 20190102C & 0.291 & 312.6537 & -33.4931 & 363.6 & 276.2 & 290.32 & \\citet{2020Nature_Macquart} \\\\\nFRB 20190110C & 0.12244 & 65.6 & 42.1 & 221.6 & 154.53 & 161.65 & \\citet{Ibik_2024} \\\\\nFRB 20190303A & 0.064 & 97.5 & 65.7 & 222.4 & 162.73 & 170.57 & \\citet{Michilli_2023} \\\\\nFRB 20190418A & 0.07132 & 179.3 & -22.93 & 184.5 & 84.39 & 68.9 & \\citet{Bhardwaj_2024} \\\\\nFRB 20190425A & 0.03122 & 42.06 & 33.02 & 128.2 & 49.4 & 59.39 & \\citet{Bhardwaj_2024} \\\\\nFRB 20190520B & 0.241 & 359.67 & 29.91 & 1204.7 & 1114.49 & 1124.47 & \\citet{2022Nature_CHNiu} \\\\\nFRB 20190523A & 0.66 & 117.03 & 44.0 & 760.8 & 693.62 & 700.92 & \\citet{2019Nature_Ravi} \\\\\nFRB 20190608B & 0.1178 & 53.2088 & -48.5296 & 338.7 & 271.43 & 282.08 & \\citet{2025ASKAP} \\\\\nFRB 20190611B & 0.3778 & 312.9352 & -33.2818 & 321.4 & 233.57 & 247.73 & \\citet{2025ASKAP} \\\\\nFRB 20190614D & 0.6 & 136.3 & 16.5 & 959.2 & 841.2 & 820.14 & \\citet{Law_2020} \\\\\nFRB 20190711A & 0.522 & 310.9081 & -33.902 & 593.1 & 506.61 & 520.49 & \\citet{2025ASKAP} \\\\\nFRB 20190714A & 0.2365 & 289.6972 & 48.9359 & 504.0 & 435.51 & 442.84 & \\citet{2025ASKAP} \\\\\nFRB 20191001A & 0.234 & 341.2267 & -44.9039 & 506.92 & 432.75 & 445.84 & \\citet{2025ASKAP} \\\\\nFRB 20191106C & 0.10775 & 105.7 & 73.2 & 332.2 & 277.19 & 281.66 & \\citet{Ibik_2024} \\\\\nFRB 20191228A & 0.2432 & 20.5553 & -64.9245 & 297.5 & 234.55 & 247.58 & \\citet{Bhandari_2022} \\\\\nFRB 20200120E & 0.0008 & 142.19 & 41.22 & 87.82 & 17.15 & 25.59 & \\citet{Bhardwaj_2021} \\\\\nFRB 20200223B & 0.0602 & 118.1 & -33.9 & 201.8 & 126.27 & 134.81 & \\citet{Ibik_2024} \\\\\nFRB 20200430A & 0.16 & 17.1396 & 52.503 & 380.1 & 322.92 & 324.02 & \\citet{2025ASKAP} \\\\\nFRB 20200906A & 0.3688 & 202.257 & -49.9989 & 577.8 & 511.96 & 509.93 & \\citet{Bhandari_2022} \\\\\nFRB 20201123A & 0.05 & 340.23 & -9.68 & 433.55 & 151.89 & 240.89 & \\citet{2022MNRAS_Rajwade} \\\\\nFRB 20201124A & 0.098 & 177.6 & -8.5 & 413.52 & 243.39 & 186.83 & \\citet{2022MNRAS_Ravi} \\\\\nFRB 20210117A & 0.2145 & 45.9175 & -57.6464 & 730.0 & 665.62 & 676.9 & \\citet{Bhandari_2023} \\\\\nFRB 20210320C & 0.2797 & 318.8729 & 45.3081 & 384.8 & 315.51 & 324.41 & \\citet{2023ApJ_Garden} \\\\\nFRB 20210405I & 0.066 & 338.19 & -4.59 & 565.17 & 18.39 & 185.96 & \\citet{2024MNRAS20210405I} \\\\\nFRB 20210410D & 0.1415 & 312.32 & -34.13 & 578.78 & 492.59 & 506.54 & \\citet{2023MNRAS.524.2064C} \\\\\nFRB 20210603A & 0.177 & 119.71 & -41.58 & 500.147 & 430.61 & 439.36 & \\citet{2024NatAs...8.1429C} \\\\\nFRB 20210807D & 0.12927 & 39.8612 & -14.8775 & 251.9 & 100.73 & 128.24 & \\citet{2025ASKAP} \\\\\nFRB 20211127I & 0.0469 & 312.0214 & 43.5427 & 234.83 & 162.36 & 173.37 & \\citet{2025ASKAP} \\\\\nFRB 20211203C & 0.3437 & 314.5185 & 30.4361 & 636.2 & 542.47 & 557.82 & \\citet{2025ASKAP} \\\\\nFRB 20211212A & 0.0715 & 244.0081 & 47.3154 & 206.0 & 137.25 & 148.54 & \\citet{2025ASKAP} \\\\\nFRB 20220105A & 0.2785 & 18.555 & 74.808 & 583.0 & 530.96 & 532.37 & \\citet{2025ASKAP} \\\\\nFRB 20220204A & 0.4012 & 102.26 & 27.06 & 612.2 & 529.36 & 533.5 & \\citet{Sharma1} \\\\\nFRB 20220207C & 0.0433 & 106.94 & 18.39 & 262.3 & 156.2 & 149.03 & \\citet{Sharma1} \\\\\nFRB 20220208A & 0.351 & 107.62 & 15.36 & 437.0 & 316.6 & 299.08 & \\citet{Sharma1} \\\\\nFRB 20220307B & 0.2481 & 116.24 & 10.47 & 499.15 & 340.9 & 282.17 & \\citet{Sharma1} \\\\\nFRB 20220310F & 0.478 & 140.02 & 34.8 & 462.15 & 385.81 & 392.64 & \\citet{Sharma1} \\\\\nFRB 20220319D & 0.011 & 129.18 & 9.11 & 110.95 & -58.76 & -130.01 & \\citet{2025AJ_Ravi} \\\\\nFRB 20220330D & 0.3714 & 134.18 & 42.93 & 468.1 & 399.12 & 407.47 & \\citet{Sharma1} \\\\\nFRB 20220418A & 0.6213 & 110.75 & 44.47 & 623.45 & 556.8 & 563.91 & \\citet{Sharma1} \\\\\nFRB 20220501C & 0.381 & 11.1777 & -71.4731 & 449.5 & 388.88 & 405.5 & \\citet{2025ASKAP} \\\\\nFRB 20220506D & 0.3004 & 108.35 & 16.51 & 369.93 & 255.35 & 242.24 & \\citet{Sharma1} \\\\\nFRB 20220509G & 0.0894 & 100.94 & 25.48 & 269.5 & 183.9 & 187.44 & \\citet{Sharma1} \\\\\nFRB 20220529A & 0.1839 & 130.78767 & -41.85802 & 246.0 & 176.05 & 185.08 & \\citet{2025arXiv_YeLi} \\\\\nFRB 20220610A & 1.017 & 8.8392 & -70.1857 & 1458.0 & 1397.04 & 1414.42 & \\citet{2025ASKAP} \\\\\nFRB 20220610A & 1.016 & 8.8392 & -70.1857 & 1458.15 & 1397.19 & 1414.57 & \\citet{2025ASKAP} \\\\\nFRB 20220717A & 0.36295 & 19.83515767 & -17.63203224 & 637.34 & 489.01 & 524.12 & \\citet{2024MNRAS_2trb_sys} \\\\\nFRB 20220725A & 0.1962 & 0.0017 & -71.1863 & 290.4 & 229.67 & 248.82 & \\citet{2025ASKAP} \\\\\nFRB 20220726A & 0.3619 & 139.97 & 17.57 & 686.55 & 572.9 & 555.41 & \\citet{Sharma1} \\\\\nFRB 20220825A & 0.2414 & 106.99 & 17.79 & 651.2 & 542.74 & 534.29 & \\citet{Sharma1} \\\\\nFRB 20220831A & 0.262 & 110.96 & 12.47 & 1146.25 & 1006.04 & 968.48 & \\citet{Sharma1} \\\\\nFRB 20220912A & 0.077 & 347.27 & 48.7 & 651.24 & 588.74 & 592.64 & \\citet{2023ApJ_20220912A} \\\\\nFRB 20220914A & 0.1139 & 104.31 & 26.13 & 631.05 & 546.37 & 549.94 & \\citet{Sharma1} \\\\\nFRB 20220918A & 0.491 & 300.6851 & -46.2342 & 656.8 & 586.06 & 597.93 & \\citet{2025ASKAP} \\\\\nFRB 20220920A & 0.1582 & 104.92 & 38.89 & 315.0 & 245.14 & 251.64 & \\citet{Sharma1} \\\\\nFRB 20221012A & 0.2847 & 101.14 & 26.14 & 441.2 & 356.85 & 360.65 & \\citet{Sharma1} \\\\\nFRB 20221027A & 0.5422 & 142.66 & 33.96 & 452.5 & 374.88 & 381.43 & \\citet{Sharma1} \\\\\nFRB 20221029A & 0.975 & 140.39 & 38.01 & 1391.05 & 1317.9 & 1325.63 & \\citet{Sharma1} \\\\\nFRB 20221101B & 0.2395 & 113.25 & 11.06 & 490.7 & 338.02 & 286.5 & \\citet{Sharma1} \\\\\nFRB 20221106A & 0.2044 & 220.901 & -50.8788 & 314.99 & 250.2 & 253.15 & \\citet{2025ASKAP} \\\\\nFRB 20221113A & 0.2505 & 139.53 & 16.99 & 411.027 & 294.72 & 275.5 & \\citet{Sharma1} \\\\\nFRB 20221116A & 0.2764 & 124.47 & 8.71 & 643.448 & 468.4 & 389.96 & \\citet{Sharma1} \\\\\nFRB 20221219A & 0.553 & 103.19 & 34.07 & 706.708 & 632.74 & 638.73 & \\citet{Sharma1} \\\\\nFRB 20230124A & 0.0939 & 107.55 & 40.25 & 590.574 & 521.44 & 528.22 & \\citet{Sharma1} \\\\\nFRB 20230203A & 0.1464 & 188.7125372 & 54.08702676 & 420.1 & 353.84 & 367.15 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20230216A & 0.531 & 242.6 & 46.33 & 828.0 & 758.54 & 769.85 & \\citet{Sharma1} \\\\\nFRB 20230222A & 0.1223 & 204.7163778 & 8.695736261 & 706.1 & 541.9 & 488.02 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20230222B & 0.11 & 49.61758206 & 49.97872118 & 187.8 & 130.07 & 131.51 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20230307A & 0.2706 & 127.35 & 45.0 & 608.854 & 541.46 & 549.6 & \\citet{Sharma1} \\\\\nFRB 20230311A & 0.1918 & 157.7133766 & 16.03946791 & 364.3 & 241.84 & 218.62 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20230501A & 0.3015 & 112.43 & 11.51 & 532.471 & 383.92 & 337.25 & \\citet{Sharma1} \\\\\nFRB 20230521B & 1.354 & 115.65 & 9.97 & 1342.9 & 1179.5 & 1115.1 & \\citet{Sharma1} \\\\\nFRB 20230526A & 0.157 & 290.171 & -63.4721 & 361.4 & 299.54 & 309.54 & \\citet{2025ASKAP} \\\\\nFRB 20230626A & 0.327 & 105.68 & 38.34 & 361.4 & 291.19 & 297.55 & \\citet{Sharma1} \\\\\nFRB 20230628A & 0.127 & 135.48 & 42.21 & 344.952 & 275.36 & 283.78 & \\citet{Sharma1} \\\\\nFRB 20230703A & 0.1184 & 137.2097857 & 67.47502062 & 291.3 & 234.37 & 240.63 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20230708A & 0.105 & 342.6288 & -33.3877 & 411.51 & 321.18 & 337.52 & \\citet{2025ASKAP} \\\\\nFRB 20230712A & 0.4525 & 132.31 & 43.69 & 587.567 & 519.13 & 527.47 & \\citet{Sharma1} \\\\\nFRB 20230718A & 0.0357 & 259.4629 & -0.3666 & 476.6 & 25.95 & -3.39 & \\citet{2025ASKAP} \\\\\nFRB 20230730A & 0.2115 & 158.8166352 & -17.81644809 & 312.5 & 197.34 & 185.12 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20230814A & 0.553 & 112.56 & 13.2 & 696.4 & 561.64 & 528.61 & \\citet{Sharma1} \\\\\nFRB 20230902A & 0.3619 & 256.9906 & -53.3387 & 440.1 & 375.96 & 384.57 & \\citet{2025ASKAP} \\\\\nFRB 20230926A & 0.0553 & 68.23527902 & 27.48398452 & 222.8 & 140.18 & 149.08 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231005A & 0.0713 & 57.16529291 & 44.35315679 & 189.4 & 125.93 & 130.61 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231011A & 0.0783 & 127.2286992 & -20.94298363 & 186.3 & 85.95 & 90.61 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231017A & 0.245 & 100.6098004 & -21.65190357 & 344.2 & 249.65 & 258.56 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231025B & 0.3238 & 93.43324314 & 29.43399566 & 368.7 & 290.11 & 295.33 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231120A & 0.0368 & 140.43 & 37.94 & 438.9 & 365.68 & 373.4 & \\citet{Sharma1} \\\\\nFRB 20231123A & 0.0729 & 199.3094435 & -15.74274898 & 302.1 & 182.35 & 135.24 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231123B & 0.2621 & 105.71 & 38.38 & 396.857 & 326.5 & 333.04 & \\citet{Sharma1} \\\\\nFRB 20231128A & 0.1079 & 105.6852393 & 73.2240021 & 331.6 & 276.59 & 281.06 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231201A & 0.1119 & 163.0405249 & -22.7702363 & 169.4 & 69.45 & 64.68 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231204A & 0.0644 & 97.62375629 & 65.92814517 & 221.0 & 161.17 & 169.21 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231206A & 0.0659 & 161.0581675 & 27.48189499 & 457.7 & 368.56 & 368.41 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231220A & 0.3355 & 143.29 & 31.69 & 491.2 & 410.93 & 416.03 & \\citet{Sharma1} \\\\\nFRB 20231223C & 0.1059 & 52.31072392 & 32.08016178 & 165.8 & 87.93 & 97.16 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231226A & 0.1569 & 236.5768 & 48.6458 & 329.9 & 261.81 & 273.21 & \\citet{2025ASKAP} \\\\\nFRB 20231229A & 0.019 & 135.344911 & -26.44334852 & 198.5 & 110.32 & 116.73 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20231230A & 0.0298 & 195.8701482 & -25.2386886 & 131.4 & 39.82 & 18.13 & \\citet{2025arXiv_CHIME_localized} \\\\\nFRB 20240114A & 0.42 & 57.73 & -31.68 & 527.7 & 448.28 & 458.93 & \\citet{2024ApJ_20240114A} \\\\\nFRB 20240119A & 0.376 & 112.37 & 43.24 & 483.1 & 415.74 & 422.78 & \\citet{Sharma1} \\\\\nFRB 20240123A & 0.968 & 138.14 & 15.34 & 1462.0 & 1337.98 & 1312.29 & \\citet{Sharma1} \\\\\nFRB 20240201A & 0.042729 & 222.1335 & 47.9692 & 374.5 & 305.88 & 315.36 & \\citet{2025ASKAP} \\\\\nFRB 20240210A & 0.023686 & 14.4396 & -86.2116 & 283.8 & 225.11 & 235.9 & \\citet{2025ASKAP} \\\\\nFRB 20240213A & 0.1185 & 136.49 & 41.57 & 357.4 & 287.3 & 295.64 & \\citet{Sharma1} \\\\\nFRB 20240215A & 0.21 & 102.29 & 30.17 & 549.5 & 471.21 & 476.39 & \\citet{Sharma1} \\\\\nFRB 20240229A & 0.287 & 131.13 & 44.11 & 491.15 & 423.21 & 431.34 & \\citet{Sharma1} \\\\\nFRB 20240310A & 0.127 & 291.7066 & -72.2713 & 601.8 & 541.7 & 551.97 & \\citet{2025ASKAP} \\\\\n\\enddata\n\\end{deluxetable}'