In [1]:
import sys
sys.path.append('../../Python_scripts')

## Import packages
from config import *
from support import *
from cosmo_support import *
import csv_to_latex as to_latex

/home/zhuge/miniconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
data=pd.read_csv('../../Data/FRB_new.csv')
print(data.columns)
data.head()

Index(['FRB', 'z', 'gl', 'gb', 'DM', 'DM_MW, ISM(NE2001)', 'DM_MW, ISM(YMW16)',
       'DM_ext(ne2001)', 'DM_ext(ymw16)', 'Ref.'],
      dtype='object')

,FRB,z,gl,gb,DM,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16),Ref.
0,FRB 20180814A,0.06800,136.460000,16.580000,190.90,87.83,108.41,73.073904,52.493323,CHIME13
1,FRB 20181030A,0.00385,133.400000,40.900000,103.50,40.35,32.24,33.149498,41.256729,181030A
2,FRB 20220529A,0.18390,130.787670,-41.858020,246.00,39.95,30.92,176.048832,185.076405,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01500,8.839200,-70.185700,1458.10,30.96,13.58,1397.142120,1414.521089,ASKAP2
4,FRB 20220717A,0.36295,19.835158,-17.632032,637.34,118.33,83.22,489.008396,524.116215,https://arxiv.org/pdf/2407.02173

In [3]:
data=data[['FRB', 'z','gl', 'gb','DM', 'DM_MW, ISM(NE2001)', 'DM_MW, ISM(YMW16)', 'Ref.']]
data.head()

,FRB,z,gl,gb,DM,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",Ref.
0,FRB 20180814A,0.06800,136.460000,16.580000,190.90,87.83,108.41,CHIME13
1,FRB 20181030A,0.00385,133.400000,40.900000,103.50,40.35,32.24,181030A
2,FRB 20220529A,0.18390,130.787670,-41.858020,246.00,39.95,30.92,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01500,8.839200,-70.185700,1458.10,30.96,13.58,ASKAP2
4,FRB 20220717A,0.36295,19.835158,-17.632032,637.34,118.33,83.22,https://arxiv.org/pdf/2407.02173

In [4]:
import re
def frb_sort_key(frb_str):
    match = re.search(r'FRB\s*(\d+)([A-Z]+)', frb_str)
    if match:
        number = int(match.group(1))
        letter = match.group(2)
        return (number, letter)
    return (0, 'Z')
data_sorted = data.sort_values('FRB', key=lambda x: x.apply(frb_sort_key)).reset_index(drop=True)
data_sorted.head()

,FRB,z,gl,gb,DM,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",Ref.
0,FRB 20121102A,0.19273,174.890,-0.230,557.00,188.42,287.07,https://iopscience.iop.org/article/10.1088/000...
1,FRB 20171020A,0.00867,29.300,-51.300,114.10,38.37,25.84,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20180301A,0.33040,204.412,-6.481,522.00,150.73,252.56,https://iopscience.iop.org/article/10.3847/153...
3,FRB 20180814A,0.06800,136.460,16.580,190.90,87.83,108.41,CHIME13
4,FRB 20180916B,0.03380,129.710,3.730,348.76,198.91,324.82,180916B

In [5]:
data_sorted['gl']=data_sorted['gl'].round(4)
data_sorted['gb']=data_sorted['gb'].round(4)
data_sorted.head()

,FRB,z,gl,gb,DM,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",Ref.
0,FRB 20121102A,0.19273,174.890,-0.230,557.00,188.42,287.07,https://iopscience.iop.org/article/10.1088/000...
1,FRB 20171020A,0.00867,29.300,-51.300,114.10,38.37,25.84,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20180301A,0.33040,204.412,-6.481,522.00,150.73,252.56,https://iopscience.iop.org/article/10.3847/153...
3,FRB 20180814A,0.06800,136.460,16.580,190.90,87.83,108.41,CHIME13
4,FRB 20180916B,0.03380,129.710,3.730,348.76,198.91,324.82,180916B

In [6]:
citation_dict={
    '180916B':'2020Nature_180916, Tendulkar_2021_180916, Kaur_2022_180916',
    '181030A':'Bhardwaj_2021_181030A',
    'https://iopscience.iop.org/article/10.1088/0004-637X/790/2/101': '2017Nature_121102, Tendulkar_2017_121102', # FRB 121102
    'https://www.nature.com/articles/s41586-018-0864-x': '2019Nature_CHIME',
    'https://iopscience.iop.org/article/10.3847/2041-8213/ab4a80':'Andersen_2019',
    'https://arxiv.org/abs/2503.04727': '2025arXiv_YeLi',
    'ASKAP':'2025ASKAP',
    'ASKAP2':'2025ASKAP, highres_ASKAP_arxiv2025',
    'https://arxiv.org/pdf/2407.02173':'2024MNRAS_2trb_sys',
    'https://www.nature.com/articles/s41586-018-0588-y':'2018Nature171020',
    'https://academic.oup.com/mnras/article/486/3/3636/5432360?login=false':'2019MNRAS_180301',
    'https://www.science.org/doi/10.1126/science.aaw5903':'2019Science180924, 2020Nature_Macquart, Bhandari_2020, 2023ApJ_Garden, 2025ASKAP, highres_ASKAP_arxiv2025',# here
    'https://www.science.org/doi/10.1126/science.aay0073':'2019Science181112, 2020Nature_Macquart, Bhandari_2020, 2025ASKAP, highres_ASKAP_arxiv2025',
    'CHIME4':'Bhardwaj_2024',
    'CHIME_host':'Ibik_2024',
    'CHIME13':'Michilli_2023',
    '190608B':'2020Nature_Macquart, Bhandari_2020, 2023ApJ_Garden, 2025ASKAP, highres_ASKAP_arxiv2025',
    '290611B':'Heintz_2020, 2020Nature_Macquart, 2025ASKAP, highres_ASKAP_arxiv2025',
    '190711A':'Heintz_2020, 2020Nature_Macquart, 2025ASKAP, highres_ASKAP_arxiv2025',
    '190714A':'Heintz_2020, 2025ASKAP, highres_ASKAP_arxiv2025',
    '191001A':'Heintz_2020, 2025ASKAP, highres_ASKAP_arxiv2025',
    '191228A':'Bhandari_2022, 2025ASKAP, highres_ASKAP_arxiv2025',
    '200430A':'Heintz_2020, 2025ASKAP, highres_ASKAP_arxiv2025',
    '200906A':'Bhandari_2022, 2025ASKAP, highres_ASKAP_arxiv2025',
    '220501C':'2025ASKAP,Sharma, highres_ASKAP_arxiv2025',
    'https://www.nature.com/articles/s41586-022-04755-5':'2022Nature_CHNiu, 2023ApJ_Garden',
    'https://www.nature.com/articles/s41586-019-1389-7':'2019Nature_Ravi',
    'https://iopscience.iop.org/article/10.3847/1538-4357/aba4ac':'Law_2020',
    'https://iopscience.iop.org/article/10.3847/1538-3881/ac3aec':'Bhandari_2022',
    'https://academic.oup.com/mnras/article/514/2/1961/6595347?login=false':'2022MNRAS_Rajwade',
    'https://ui.adsabs.harvard.edu/abs/2022MNRAS.513..982R/abstract':'2022MNRAS_Ravi',
    'https://iopscience.iop.org/article/10.3847/1538-4357/acc178':'Bhandari_2023, 2023ApJ_Garden, 2025ASKAP, highres_ASKAP_arxiv2025',
    'https://arxiv.org/abs/2302.05465':'2023ApJ_Garden, 2025ASKAP, highres_ASKAP_arxiv2025',
    '20210405I':'2024MNRAS20210405I',
    'https://www.wis-tns.org/object/frb20210410d':'2023MNRAS.524.2064C, 2023ApJ_Garden',
    '210807D':'2023ApJ_Garden, 2025ASKAP',
    '211127I':'2023ApJ_Garden, Glowacki_2023, 2025ASKAP, highres_ASKAP_arxiv2025',
    '211203C':'2023ApJ_Garden, 2025ASKAP, highres_ASKAP_arxiv2025',
    '211212A':'2023ApJ_Garden, 2025ASKAP, highres_ASKAP_arxiv2025',
    '220105A':'2023ApJ_Garden, 2025ASKAP, highres_ASKAP_arxiv2025',
    'Kritti3':'2024ApJ_25,Sharma,Connor_Sharma', # Kritti3 24,28,29
    'Kritti4':'Sherman_2023,2024ApJ_25,Sharma,Connor_Sharma',
    'Kritti_local':'Sharma,Connor_Sharma',
    'Kritti2':'2024ApJ_25,Connor_Sharma', # Kritti2 24, 29
    'ASKAP_Kritti2':'Sharma,Connor_Sharma,2025ASKAP',
    'https://arxiv.org/abs/2307.09502':'2024NatAs...8.1429C',
    '20200120E':'Bhardwaj_2021, Glowacki_2023', # very small z in M81, change from 0.0008 to 0.00014
    'https://arxiv.org/pdf/2502.11217':'2025arXiv_CHIME_localized',
    'https://arxiv.org/pdf/2409.16952':'Connor_Sharma',
    '230521B':'Connor_Sharma,2025ASKAP',
    'https://iopscience.iop.org/article/10.3847/2041-8213/aae7cb':'Mahony_2018, 2023PASA_20171020A_revisited',
    '220319D':'Sherman_2023,2024ApJ_25,Sharma,Connor_Sharma, 2025AJ_20220319D',
    'https://www.astronomerstelegram.org/?read=15679':'2023ApJ_20220912A',
    '240114A':'2024ApJ_20240114A, Chen_2025',
    '190102C':'2020Nature_Macquart, Bhandari_2020, 2025ASKAP, highres_ASKAP_arxiv2025'
}

In [7]:
""" data_sorted['Ref.'] = data_sorted['Ref.'].astype(str)
data_sorted['Ref.'] = data_sorted['Ref.'].map(citation_dict).fillna(data_sorted['Ref.']) """

" data_sorted['Ref.'] = data_sorted['Ref.'].astype(str)\ndata_sorted['Ref.'] = data_sorted['Ref.'].map(citation_dict).fillna(data_sorted['Ref.']) "

In [8]:
data_sorted['Ref.'] = data_sorted['Ref.'].replace(citation_dict)
# data_sorted['Ref.']=r'\citet{'+data_sorted['Ref.']+'}'
data_sorted.head()

,FRB,z,gl,gb,DM,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",Ref.
0,FRB 20121102A,0.19273,174.890,-0.230,557.00,188.42,287.07,"2017Nature_121102, Tendulkar_2017_121102"
1,FRB 20171020A,0.00867,29.300,-51.300,114.10,38.37,25.84,"Mahony_2018, 2023PASA_20171020A_revisited"
2,FRB 20180301A,0.33040,204.412,-6.481,522.00,150.73,252.56,Bhandari_2022
3,FRB 20180814A,0.06800,136.460,16.580,190.90,87.83,108.41,Michilli_2023
4,FRB 20180916B,0.03380,129.710,3.730,348.76,198.91,324.82,"2020Nature_180916, Tendulkar_2021_180916, Kaur..."

In [9]:
print(data_sorted.columns)
data_sorted.rename(columns={
    'DM': r'$\DM_{\rm obs}$',
    'DM_MW, ISM(NE2001)': r'$\DM_{\rm MW, ISM}$(NE2001)',
    'DM_MW, ISM(YMW16)': r'$\DM_{\rm MW, ISM}$(YMW16)',
}, inplace=True)
data_sorted.head()

Index(['FRB', 'z', 'gl', 'gb', 'DM', 'DM_MW, ISM(NE2001)', 'DM_MW, ISM(YMW16)',
       'Ref.'],
      dtype='object')

,FRB,z,gl,gb,$\DM_{\rm obs}$,"$\DM_{\rm MW, ISM}$(NE2001)","$\DM_{\rm MW, ISM}$(YMW16)",Ref.
0,FRB 20121102A,0.19273,174.890,-0.230,557.00,188.42,287.07,"2017Nature_121102, Tendulkar_2017_121102"
1,FRB 20171020A,0.00867,29.300,-51.300,114.10,38.37,25.84,"Mahony_2018, 2023PASA_20171020A_revisited"
2,FRB 20180301A,0.33040,204.412,-6.481,522.00,150.73,252.56,Bhandari_2022
3,FRB 20180814A,0.06800,136.460,16.580,190.90,87.83,108.41,Michilli_2023
4,FRB 20180916B,0.03380,129.710,3.730,348.76,198.91,324.82,"2020Nature_180916, Tendulkar_2021_180916, Kaur..."

In [10]:
head2=r'& & (deg) & (deg) & $ (\rm pc \, cm^{-3})$ & $(\rm pc \, cm^{-3})$ & $(\rm pc \, cm^{-3})$ & '
to_latex.dataframe_to_latex_long_ref(data_sorted,'./table.tex',caption='Well localized FRB samples',label='tab:data',head2=head2)

LaTeX already save to: ./table.tex

'\\startlongtable\n\\begin{deluxetable}{cccccccc}\n\\label{tab:data}\n\\centering\n\\tablecaption{Well localized FRB samples}\n\\tablehead{\\colhead{FRB} & \\colhead{z} & \\colhead{gl} & \\colhead{gb} & \\colhead{$\\DM_{\\rm obs}$} & \\colhead{$\\DM_{\\rm MW, ISM}$(NE2001)} & \\colhead{$\\DM_{\\rm MW, ISM}$(YMW16)} & \\colhead{Ref.} \\\\\n& & (deg) & (deg) & $ (\\rm pc \\, cm^{-3})$ & $(\\rm pc \\, cm^{-3})$ & $(\\rm pc \\, cm^{-3})$ & \n}\n\\startdata\nFRB 20121102A & 0.19273 & 174.89 & -0.23 & 557.0 & 188.42 & 287.07 & 1, 40 \\\\\nFRB 20171020A & 0.00867 & 29.3 & -51.3 & 114.1 & 38.37 & 25.84 & 36, 13 \\\\\nFRB 20180301A & 0.3304 & 204.412 & -6.481 & 522.0 & 150.73 & 252.56 & 24 \\\\\nFRB 20180814A & 0.068 & 136.46 & 16.58 & 190.9 & 87.83 & 108.41 & 37 \\\\\nFRB 20180916B & 0.0338 & 129.71 & 3.73 & 348.76 & 198.91 & 324.82 & 5, 41, 34 \\\\\nFRB 20180924B & 0.3214 & 0.7424 & -49.4147 & 361.75 & 40.5 & 27.65 & 3, 6, 23, 11, 20, 42 \\\\\nFRB 20181030A & 0.00385 & 133.4 & 40.9 & 103.5 & 40.35 & 32.24 & 27 \\\\\nFRB 20181112A & 0.4755 & 342.5995 & -47.6988 & 589.0 & 41.72 & 29.03 & 4, 6, 23, 20, 42 \\\\\nFRB 20181220A & 0.02746 & 105.24 & -10.73 & 209.4 & 125.85 & 122.13 & 28 \\\\\nFRB 20181223C & 0.03024 & 207.75 & 79.51 & 112.5 & 19.93 & 19.15 & 28 \\\\\nFRB 20190102C & 0.29 & 312.6537 & -33.4931 & 364.55 & 57.4 & 43.28 & 6, 23, 20, 42 \\\\\nFRB 20190110C & 0.12244 & 65.6 & 42.1 & 221.6 & 37.07 & 29.95 & 33 \\\\\nFRB 20190303A & 0.064 & 97.5 & 65.7 & 222.4 & 29.67 & 21.83 & 37 \\\\\nFRB 20190418A & 0.07132 & 179.3 & -22.93 & 184.5 & 70.11 & 85.6 & 28 \\\\\nFRB 20190425A & 0.03122 & 42.06 & 33.02 & 128.2 & 48.8 & 38.81 & 28 \\\\\nFRB 20190520B & 0.241 & 359.67 & 29.91 & 1204.7 & 60.21 & 50.23 & 9, 11 \\\\\nFRB 20190523A & 0.66 & 117.03 & 44.0 & 760.8 & 37.18 & 29.88 & 2 \\\\\nFRB 20190608B & 0.11778 & 53.2088 & -48.5296 & 339.5 & 37.27 & 26.62 & 6, 23, 11, 20, 42 \\\\\nFRB 20190611B & 0.3778 & 312.9352 & -33.2818 & 322.4 & 57.83 & 43.67 & 32, 6, 20, 42 \\\\\nFRB 20190614D & 0.6 & 136.3 & 16.5 & 959.2 & 88.0 & 109.06 & 35 \\\\\nFRB 20190711A & 0.522 & 310.9081 & -33.902 & 592.0 & 56.49 & 42.61 & 32, 6, 20, 42 \\\\\nFRB 20190714A & 0.2365 & 289.6972 & 48.9359 & 504.7 & 38.49 & 31.16 & 32, 20, 42 \\\\\nFRB 20191001A & 0.23 & 341.2267 & -44.9039 & 507.0 & 44.17 & 31.08 & 32, 20, 42 \\\\\nFRB 20191106C & 0.10775 & 105.7 & 73.2 & 332.2 & 25.01 & 20.54 & 33 \\\\\nFRB 20191228A & 0.2432 & 20.5553 & -64.9245 & 297.0 & 32.95 & 19.92 & 24, 20, 42 \\\\\nFRB 20200120E & 0.00014 & 142.19 & 41.22 & 87.82 & 40.67 & 32.23 & 26, 31 \\\\\nFRB 20200223B & 0.06024 & 118.1 & -33.9 & 201.8 & 45.53 & 36.99 & 33 \\\\\nFRB 20200430A & 0.1608 & 17.1396 & 52.503 & 380.1 & 27.18 & 26.08 & 32, 20, 42 \\\\\nFRB 20200906A & 0.3688 & 202.257 & -49.9989 & 577.8 & 35.84 & 37.87 & 24, 20, 42 \\\\\nFRB 20201123A & 0.0507 & 340.23 & -9.68 & 433.55 & 251.66 & 162.66 & 7 \\\\\nFRB 20201124A & 0.098 & 177.6 & -8.5 & 413.52 & 140.13 & 196.69 & 8 \\\\\nFRB 20210117A & 0.214 & 45.9175 & -57.6464 & 729.2 & 34.38 & 23.1 & 25, 11, 20, 42 \\\\\nFRB 20210320C & 0.28 & 318.8729 & 45.3081 & 384.6 & 39.29 & 30.39 & 11, 20, 42 \\\\\nFRB 20210405I & 0.066 & 338.19 & -4.59 & 565.17 & 516.78 & 349.21 & 16 \\\\\nFRB 20210410D & 0.1415 & 312.32 & -34.13 & 578.78 & 56.19 & 42.24 & 12, 11 \\\\\nFRB 20210603A & 0.1772 & 119.71 & -41.58 & 500.147 & 39.53 & 30.79 & 18 \\\\\nFRB 20210807D & 0.12927 & 39.8612 & -14.8775 & 251.9 & 121.17 & 93.66 & 11, 20 \\\\\nFRB 20211127I & 0.046946 & 312.0214 & 43.5427 & 234.83 & 42.47 & 31.46 & 11, 31, 20, 42 \\\\\nFRB 20211203C & 0.3439 & 314.5185 & 30.4361 & 636.2 & 63.73 & 48.38 & 11, 20, 42 \\\\\nFRB 20211212A & 0.0707 & 244.0081 & 47.3154 & 200.0 & 38.75 & 27.46 & 11, 20, 42 \\\\\nFRB 20220105A & 0.2785 & 18.555 & 74.808 & 583.0 & 22.04 & 20.63 & 11, 20, 42 \\\\\nFRB 20220204A & 0.4012 & 102.26 & 27.06 & 612.2 & 52.84 & 48.7 & 15, 38, 30 \\\\\nFRB 20220207C & 0.0433 & 106.94 & 18.39 & 262.3 & 76.1 & 83.27 & 39, 15, 38, 30 \\\\\nFRB 20220208A & 0.351 & 107.62 & 15.36 & 437.0 & 90.4 & 107.92 & 15, 38, 30 \\\\\nFRB 20220307B & 0.2481 & 116.24 & 10.47 & 499.15 & 128.25 & 186.98 & 39, 15, 38, 30 \\\\\nFRB 20220310F & 0.478 & 140.02 & 34.8 & 462.15 & 46.34 & 39.51 & 39, 15, 38, 30 \\\\\nFRB 20220319D & 0.0112 & 129.18 & 9.11 & 110.95 & 139.71 & 210.96 & 39, 15, 38, 30, 19 \\\\\nFRB 20220330D & 0.3714 & 134.18 & 42.93 & 468.1 & 38.98 & 30.63 & 15, 38, 30 \\\\\nFRB 20220418A & 0.6213 & 110.75 & 44.47 & 623.45 & 36.65 & 29.54 & 39, 15, 38, 30 \\\\\nFRB 20220501C & 0.381 & 11.1777 & -71.4731 & 449.5 & 30.62 & 14.0 & 20, 38, 42 \\\\\nFRB 20220506D & 0.3004 & 108.35 & 16.51 & 369.93 & 84.58 & 97.69 & 39, 15, 38, 30 \\\\\nFRB 20220509G & 0.0894 & 100.94 & 25.48 & 269.5 & 55.6 & 52.06 & 39, 15, 38, 30 \\\\\nFRB 20220529A & 0.1839 & 130.7877 & -41.858 & 246.0 & 39.95 & 30.92 & 22 \\\\\nFRB 20220610A & 1.015 & 8.8392 & -70.1857 & 1458.1 & 30.96 & 13.58 & 20, 42 \\\\\nFRB 20220717A & 0.36295 & 19.8352 & -17.632 & 637.34 & 118.33 & 83.22 & 17 \\\\\nFRB 20220725A & 0.1962 & 0.0017 & -71.1863 & 290.1 & 30.73 & 11.58 & 20, 42 \\\\\nFRB 20220726A & 0.3619 & 139.97 & 17.57 & 686.55 & 83.65 & 101.14 & 15, 38, 30 \\\\\nFRB 20220825A & 0.2414 & 106.99 & 17.79 & 651.2 & 78.46 & 86.91 & 39, 15, 38, 30 \\\\\nFRB 20220831A & 0.262 & 110.96 & 12.47 & 1146.25 & 110.21 & 147.77 & 30 \\\\\nFRB 20220912A & 0.0771 & 347.27 & 48.7 & 219.46 & 32.5 & 28.6 & 10 \\\\\nFRB 20220914A & 0.1139 & 104.31 & 26.13 & 631.05 & 54.68 & 51.11 & 15, 38, 30 \\\\\nFRB 20220918A & 0.491 & 300.6851 & -46.2342 & 643.0 & 40.74 & 28.87 & 20, 42 \\\\\nFRB 20220920A & 0.1582 & 104.92 & 38.89 & 315.0 & 39.86 & 33.36 & 39, 15, 38, 30 \\\\\nFRB 20221012A & 0.2847 & 101.14 & 26.14 & 442.2 & 54.35 & 50.55 & 39, 15, 38, 30 \\\\\nFRB 20221027A & 0.5422 & 142.66 & 33.96 & 452.5 & 47.62 & 41.07 & 15, 38, 30 \\\\\nFRB 20221029A & 0.975 & 140.39 & 38.01 & 1391.05 & 43.15 & 35.42 & 15, 38, 30 \\\\\nFRB 20221101B & 0.2395 & 113.25 & 11.06 & 490.7 & 122.68 & 174.2 & 15, 38, 30 \\\\\nFRB 20221106A & 0.2044 & 220.901 & -50.8788 & 343.2 & 34.79 & 31.84 & 20, 42 \\\\\nFRB 20221113A & 0.2505 & 139.53 & 16.99 & 411.4 & 86.31 & 105.52 & 38, 30 \\\\\nFRB 20221116A & 0.2764 & 124.47 & 8.71 & 640.6 & 145.05 & 223.48 & 38, 30, 20 \\\\\nFRB 20221219A & 0.553 & 103.19 & 34.07 & 706.708 & 43.97 & 37.98 & 38, 30 \\\\\nFRB 20230124A & 0.0939 & 107.55 & 40.25 & 590.574 & 39.13 & 32.36 & 38, 30 \\\\\nFRB 20230203A & 0.1464 & 188.7125 & 54.087 & 420.1 & 36.26 & 22.95 & 21 \\\\\nFRB 20230216A & 0.531 & 242.6 & 46.33 & 828.0 & 39.46 & 28.15 & 38, 30 \\\\\nFRB 20230222A & 0.1223 & 204.7164 & 8.6957 & 706.1 & 134.2 & 188.08 & 21 \\\\\nFRB 20230222B & 0.11 & 49.6176 & 49.9787 & 187.8 & 27.73 & 26.29 & 21 \\\\\nFRB 20230307A & 0.2706 & 127.35 & 45.0 & 608.854 & 37.4 & 29.26 & 38, 30 \\\\\nFRB 20230311A & 0.1918 & 157.7134 & 16.0395 & 364.3 & 92.46 & 115.68 & 21 \\\\\nFRB 20230501A & 0.3015 & 112.43 & 11.51 & 532.471 & 118.55 & 165.22 & 38, 30 \\\\\nFRB 20230521B & 1.354 & 115.65 & 9.97 & 1342.9 & 133.4 & 197.8 & 30 \\\\\nFRB 20230526A & 0.157 & 290.171 & -63.4721 & 316.2 & 31.86 & 21.86 & 20, 42 \\\\\nFRB 20230626A & 0.327 & 105.68 & 38.34 & 451.2 & 40.21 & 33.85 & 38, 30 \\\\\nFRB 20230628A & 0.127 & 135.48 & 42.21 & 344.952 & 39.59 & 31.17 & 38, 30 \\\\\nFRB 20230703A & 0.1184 & 137.2098 & 67.475 & 291.3 & 26.93 & 20.67 & 21 \\\\\nFRB 20230708A & 0.105 & 342.6288 & -33.3877 & 411.51 & 60.33 & 43.99 & 20, 42 \\\\\nFRB 20230712A & 0.4525 & 132.31 & 43.69 & 587.567 & 38.44 & 30.1 & 38, 30 \\\\\nFRB 20230718A & 0.035 & 259.4629 & -0.3666 & 476.67 & 420.65 & 449.99 & 20, 42 \\\\\nFRB 20230730A & 0.2115 & 158.8166 & -17.8164 & 312.5 & 85.16 & 97.38 & 21 \\\\\nFRB 20230814A & 0.553 & 112.56 & 13.2 & 696.4 & 104.76 & 137.79 & 30 \\\\\nFRB 20230814B & 0.5535 & 111.25 & 12.26 & 696.4 & 111.87 & 151.38 & 30 \\\\\nFRB 20230902A & 0.3619 & 256.9906 & -53.3387 & 440.1 & 34.14 & 25.53 & 20, 42 \\\\\nFRB 20230926A & 0.0553 & 68.2353 & 27.484 & 222.8 & 52.62 & 43.72 & 21 \\\\\nFRB 20231005A & 0.0713 & 57.1653 & 44.3532 & 189.4 & 33.47 & 28.79 & 21 \\\\\nFRB 20231011A & 0.0783 & 127.2287 & -20.943 & 186.3 & 70.35 & 65.69 & 21 \\\\\nFRB 20231017A & 0.245 & 100.6098 & -21.6519 & 344.2 & 64.55 & 55.64 & 21 \\\\\nFRB 20231025B & 0.3238 & 93.4332 & 29.434 & 368.7 & 48.59 & 43.37 & 21 \\\\\nFRB 20231120A & 0.0368 & 140.43 & 37.94 & 438.9 & 43.22 & 35.5 & 38, 30 \\\\\nFRB 20231123A & 0.0729 & 199.3094 & -15.7427 & 302.1 & 89.75 & 136.86 & 21 \\\\\nFRB 20231123B & 0.2621 & 105.71 & 38.38 & 396.857 & 40.36 & 33.82 & 38, 30 \\\\\nFRB 20231128A & 0.1079 & 105.6852 & 73.224 & 331.6 & 25.01 & 20.54 & 21 \\\\\nFRB 20231201A & 0.1119 & 163.0405 & -22.7702 & 169.4 & 69.95 & 74.72 & 21 \\\\\nFRB 20231204A & 0.0644 & 97.6238 & 65.9281 & 221.0 & 29.83 & 21.79 & 21 \\\\\nFRB 20231206A & 0.0659 & 161.0582 & 27.4819 & 457.7 & 59.14 & 59.29 & 21 \\\\\nFRB 20231220A & 0.3355 & 143.29 & 31.69 & 491.2 & 50.27 & 45.17 & 30 \\\\\nFRB 20231223C & 0.1059 & 52.3107 & 32.0802 & 165.8 & 47.87 & 38.64 & 21 \\\\\nFRB 20231226A & 0.1569 & 236.5768 & 48.6458 & 329.9 & 38.09 & 26.69 & 20, 42 \\\\\nFRB 20231229A & 0.019 & 135.3449 & -26.4433 & 198.5 & 58.18 & 51.77 & 21 \\\\\nFRB 20231230A & 0.0298 & 195.8701 & -25.2387 & 131.4 & 61.58 & 83.27 & 21 \\\\\nFRB 20240114A & 0.1306 & 57.73 & -31.68 & 527.7 & 49.42 & 38.77 & 14, 29 \\\\\nFRB 20240119A & 0.376 & 112.37 & 43.24 & 483.1 & 37.36 & 30.32 & 30 \\\\\nFRB 20240123A & 0.968 & 138.14 & 15.34 & 1462.0 & 94.02 & 119.71 & 30 \\\\\nFRB 20240201A & 0.042729 & 222.1335 & 47.9692 & 374.5 & 38.62 & 29.14 & 20, 42 \\\\\nFRB 20240210A & 0.023686 & 14.4396 & -86.2116 & 283.73 & 28.69 & 17.9 & 20, 42 \\\\\nFRB 20240213A & 0.1185 & 136.49 & 41.57 & 357.4 & 40.1 & 31.76 & 30 \\\\\nFRB 20240215A & 0.21 & 102.29 & 30.17 & 549.5 & 48.29 & 43.11 & 30 \\\\\nFRB 20240229A & 0.287 & 131.13 & 44.11 & 491.15 & 37.94 & 29.81 & 30 \\\\\nFRB 20240310A & 0.127 & 291.7066 & -72.2713 & 601.8 & 30.1 & 19.83 & 20, 42 \\\\\n\\enddata\n\\tablecomments{Reference: (1) \\citet{2017Nature_121102}; (2) \\citet{2019Nature_Ravi}; (3) \\citet{2019Science180924}; (4) \\citet{2019Science181112}; (5) \\citet{2020Nature_180916}; (6) \\citet{2020Nature_Macquart}; (7) \\citet{2022MNRAS_Rajwade}; (8) \\citet{2022MNRAS_Ravi}; (9) \\citet{2022Nature_CHNiu}; (10) \\citet{2023ApJ_20220912A}; (11) \\citet{2023ApJ_Garden}; (12) \\citet{2023MNRAS.524.2064C}; (13) \\citet{2023PASA_20171020A_revisited}; (14) \\citet{2024ApJ_20240114A}; (15) \\citet{2024ApJ_25}; (16) \\citet{2024MNRAS20210405I}; (17) \\citet{2024MNRAS_2trb_sys}; (18) \\citet{2024NatAs...8.1429C}; (19) \\citet{2025AJ_20220319D}; (20) \\citet{2025ASKAP}; (21) \\citet{2025arXiv_CHIME_localized}; (22) \\citet{2025arXiv_YeLi}; (23) \\citet{Bhandari_2020}; (24) \\citet{Bhandari_2022}; (25) \\citet{Bhandari_2023}; (26) \\citet{Bhardwaj_2021}; (27) \\citet{Bhardwaj_2021_181030A}; (28) \\citet{Bhardwaj_2024}; (29) \\citet{Chen_2025}; (30) \\citet{Connor_Sharma}; (31) \\citet{Glowacki_2023}; (32) \\citet{Heintz_2020}; (33) \\citet{Ibik_2024}; (34) \\citet{Kaur_2022_180916}; (35) \\citet{Law_2020}; (36) \\citet{Mahony_2018}; (37) \\citet{Michilli_2023}; (38) \\citet{Sharma}; (39) \\citet{Sherman_2023}; (40) \\citet{Tendulkar_2017_121102}; (41) \\citet{Tendulkar_2021_180916}; (42) \\citet{highres_ASKAP_arxiv2025}}\n\\end{deluxetable}'