Recalculate all $DM_{MW,ISM}$ based on our (gl, gb) and pygedm (see `ne2001_compare.ipynb`)

In [1]:
import sys
sys.path.append('../../Python_scripts')

## Import packages
from config import *
from support import *
from cosmo_support import *
import seaborn as sns

import pygedm

/home/zhuge/miniconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

load data

In [2]:
data=pd.read_csv('../../Data/FRB.csv')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.
0,FRB 20180814A,0.06800,190.90,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,CHIME13
1,FRB 20181030A,0.00385,103.50,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,181030A
2,FRB 20220529A,0.18390,246.00,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01500,1458.10,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,ASKAP2
4,FRB 20220717A,0.36295,637.34,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173

In [3]:
cosmo = Planck18

In [4]:
for idx in range(len(data)):
    dis=cosmo.luminosity_distance(data['z'].iloc[idx])/u.Mpc
    data.loc[idx,'DM_MW, ISM(NE2001)'] = pygedm.dist_to_dm(gl=data['gl'].iloc[idx], 
                            gb=data['gb'].iloc[idx], 
                            dist=dis.value*1e6, 
                            method='ne2001')[0].value
    data.loc[idx,'DM_MW, ISM(YMW16)'] = pygedm.dist_to_dm(gl=data['gl'].iloc[idx], 
                            gb=data['gb'].iloc[idx], 
                            dist=dis.value*1e6, 
                            method='ymw16')[0].value
data.head()

/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)"
0,FRB 20180814A,0.06800,190.90,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,CHIME13,87.826096,108.406677
1,FRB 20181030A,0.00385,103.50,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,181030A,40.350502,32.243271
2,FRB 20220529A,0.18390,246.00,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.951168,30.923595
3,FRB 20220610A,1.01500,1458.10,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,ASKAP2,30.957880,13.578911
4,FRB 20220717A,0.36295,637.34,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.331604,83.223785

In [5]:
DM_MW_halo=30
data['DM_ext(ne2001)'] = data['DM']-DM_MW_halo-data['DM_MW, ISM(NE2001)'] #apply(lambda x: f'{x:.2f}')
data['DM_ext(ymw16)'] = data['DM']-DM_MW_halo-data['DM_MW, ISM(YMW16)'] #.apply(lambda x: f'{x:.2f}')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.90,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,CHIME13,87.826096,108.406677,73.073904,52.493323
1,FRB 20181030A,0.00385,103.50,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,181030A,40.350502,32.243271,33.149498,41.256729
2,FRB 20220529A,0.18390,246.00,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.951168,30.923595,176.048832,185.076405
3,FRB 20220610A,1.01500,1458.10,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,ASKAP2,30.957880,13.578911,1397.142120,1414.521089
4,FRB 20220717A,0.36295,637.34,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.331604,83.223785,489.008396,524.116215

In [6]:
data['DM_MW, ISM(NE2001)'] = data['DM_MW, ISM(NE2001)'].round(2) #apply(lambda x: f'{x:.2f}')
data['DM_MW, ISM(YMW16)'] = data['DM_MW, ISM(YMW16)'].round(2) #.apply(lambda x: f'{x:.2f}')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.90,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,CHIME13,87.83,108.41,73.073904,52.493323
1,FRB 20181030A,0.00385,103.50,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,181030A,40.35,32.24,33.149498,41.256729
2,FRB 20220529A,0.18390,246.00,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.95,30.92,176.048832,185.076405
3,FRB 20220610A,1.01500,1458.10,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,ASKAP2,30.96,13.58,1397.142120,1414.521089
4,FRB 20220717A,0.36295,637.34,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.33,83.22,489.008396,524.116215

In [7]:
num=1
for idx in range(len(data)):
    if (np.abs(data['DM_ext(ne2001)'].iloc[idx] - data['DM_ext'].iloc[idx]) > 1) & (data['From'].iloc[idx]!='CHIME2025'):
        print(f"{num}: ({idx}){data['FRB'].iloc[idx]}: ne2001={data['DM_ext(ne2001)'].iloc[idx]:.2f} != paper {data['DM_ext'].iloc[idx]}")
        num+=1

1: (5)FRB 20220831A: ne2001=1006.04 != paper 989.45
2: (6)FRB 20230521B: ne2001=1179.50 != paper 1174.1
3: (10)FRB 20240123A: ne2001=1337.98 != paper 1341.8
4: (14)FRB 20230814B: ne2001=554.53 != paper 591.5
5: (16)FRB 20220207C: ne2001=156.20 != paper 152.98
6: (18)FRB 20220307B: ne2001=340.90 != paper 333.43
7: (22)FRB 20220506D: ne2001=255.35 != paper 277.81
8: (24)FRB 20220726A: ne2001=572.90 != paper 571.37
9: (25)FRB 20220825A: ne2001=542.74 != paper 541.5
10: (31)FRB 20221101B: ne2001=338.02 != paper 336.21
11: (32)FRB 20221113A: ne2001=295.09 != paper 293.5
12: (33)FRB 20221116A: ne2001=465.55 != paper 466.8
13: (37)FRB 20230307A: ne2001=541.46 != paper 550.65
14: (46)FRB 20180301A: ne2001=341.27 != paper 340.0
15: (49)FRB 20181112A: ne2001=517.28 != paper 457.27
16: (57)FRB 20190520B: ne2001=1114.49 != paper 1061.7
17: (60)FRB 20190611B: ne2001=234.57 != paper 233.57
18: (61)FRB 20190614D: ne2001=841.20 != paper 845.7
19: (62)FRB 20190711A: ne2001=505.51 != paper 506.7
20: (63)FRB 20190714A: ne2001=436.21 != paper 435.0
21: (71)FRB 20201124A: ne2001=243.39 != paper 260.32
22: (73)FRB 20210320C: ne2001=315.31 != paper 312.8
23: (80)FRB 20211212A: ne2001=131.25 != paper 148.9
24: (82)FRB 20220319D: ne2001=-58.76 != paper 15.7
25: (85)FRB 20220912A: ne2001=156.96 != paper 64.46
26: (86)FRB 20220918A: ne2001=572.26 != paper 585.8
27: (88)FRB 20230526A: ne2001=254.34 != paper 281.4
28: (89)FRB 20230708A: ne2001=321.18 != paper 331.51
29: (90)FRB 20230718A: ne2001=26.02 != paper 53.6
30: (92)FRB 20231226A: ne2001=261.81 != paper 154.9
31: (93)FRB 20240114A: ne2001=448.28 != paper 457.7
32: (95)FRB 20240210A: ne2001=225.04 != paper 222.73
33: (96)FRB 20240310A: ne2001=541.70 != paper 535.8

In [8]:
""" plt.figure(figsize=(14, 8))
fs=6
sns.stripplot(x=data['FRB'], y=data['DM_ext(ne2001)'], size=1, jitter=False, 
              palette='viridis', edgecolor='black', linewidth=1)
plt.title('FRB Redshift Distribution (Seaborn)', fontsize=fs+2)
plt.xlabel('FRB Name', fontsize=fs)
plt.ylabel('Redshift (z)', fontsize=fs)
plt.xticks(rotation=45, ha='right',fontsize=fs)
plt.yticks(fontsize=fs)
plt.grid(axis='y', linestyle='--', alpha=0.7) """

" plt.figure(figsize=(14, 8))\nfs=6\nsns.stripplot(x=data['FRB'], y=data['DM_ext(ne2001)'], size=1, jitter=False, \n              palette='viridis', edgecolor='black', linewidth=1)\nplt.title('FRB Redshift Distribution (Seaborn)', fontsize=fs+2)\nplt.xlabel('FRB Name', fontsize=fs)\nplt.ylabel('Redshift (z)', fontsize=fs)\nplt.xticks(rotation=45, ha='right',fontsize=fs)\nplt.yticks(fontsize=fs)\nplt.grid(axis='y', linestyle='--', alpha=0.7) "

In [9]:
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.90,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,CHIME13,87.83,108.41,73.073904,52.493323
1,FRB 20181030A,0.00385,103.50,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,181030A,40.35,32.24,33.149498,41.256729
2,FRB 20220529A,0.18390,246.00,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.95,30.92,176.048832,185.076405
3,FRB 20220610A,1.01500,1458.10,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,ASKAP2,30.96,13.58,1397.142120,1414.521089
4,FRB 20220717A,0.36295,637.34,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.33,83.22,489.008396,524.116215

In [10]:
data=data[['FRB', 'z', 'gl', 'gb', 'DM', 'DM_MW, ISM(NE2001)', 'DM_MW, ISM(YMW16)', 'DM_ext(ne2001)', 'DM_ext(ymw16)', 'Ref.']]
data.head()

,FRB,z,gl,gb,DM,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16),Ref.
0,FRB 20180814A,0.06800,136.460000,16.580000,190.90,87.83,108.41,73.073904,52.493323,CHIME13
1,FRB 20181030A,0.00385,133.400000,40.900000,103.50,40.35,32.24,33.149498,41.256729,181030A
2,FRB 20220529A,0.18390,130.787670,-41.858020,246.00,39.95,30.92,176.048832,185.076405,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01500,8.839200,-70.185700,1458.10,30.96,13.58,1397.142120,1414.521089,ASKAP2
4,FRB 20220717A,0.36295,19.835158,-17.632032,637.34,118.33,83.22,489.008396,524.116215,https://arxiv.org/pdf/2407.02173

In [11]:
data.to_csv("../../Data/FRB_new.csv",index=None)