Recalculate all $DM_{MW,ISM}$ based on our (gl, gb) and pygedm (see `ne2001_compare.ipynb`)

In [1]:
import sys
sys.path.append('../../Python_scripts')

## Import packages
from config import *
from support import *
from cosmo_support import *
import seaborn as sns

import pygedm

/home/zhuge/miniconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

load data

In [2]:
data=pd.read_csv('../../Data/FRB.csv')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173

In [3]:
cosmo = Planck18
DM_MW_halo=30

In [4]:
for idx in range(len(data)):
    dis=cosmo.luminosity_distance(data['z'].iloc[idx])/u.Mpc
    data.loc[idx,'DM_ext(ne2001)'] = data.loc[idx,'DM']-DM_MW_halo-pygedm.dist_to_dm(gl=data['gl'].iloc[idx], 
                            gb=data['gb'].iloc[idx], 
                            dist=dis.value*1e6, 
                            method='ne2001')[0].value
    data.loc[idx,'DM_ext(ymw16)'] = data.loc[idx,'DM']-DM_MW_halo-pygedm.dist_to_dm(gl=data['gl'].iloc[idx], 
                            gb=data['gb'].iloc[idx], 
                            dist=dis.value*1e6, 
                            method='ymw16')[0].value
data.head()

/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x,73.073904,52.493323
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...,33.045498,41.152729
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,176.048832,185.076405
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...,1397.192120,1414.571089
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,489.008396,524.116215

In [5]:
data['DM_ext(ne2001)'] = data['DM_ext(ne2001)'].round(2) #apply(lambda x: f'{x:.2f}')
data['DM_ext(ymw16)'] = data['DM_ext(ymw16)'].round(2) #.apply(lambda x: f'{x:.2f}')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x,73.07,52.49
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...,33.05,41.15
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,176.05,185.08
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...,1397.19,1414.57
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,489.01,524.12

In [6]:
for idx in range(len(data)):
    if np.abs(data['DM_ext(ne2001)'].iloc[idx] - data['DM_ext'].iloc[idx]) > 0.1:
        print(f"{idx}: {data['FRB'].iloc[idx]}: ne2001={data['DM_ext(ne2001)'].iloc[idx]} != paper {data['DM_ext'].iloc[idx]}")

0: FRB 20180814A: ne2001=73.07 != paper 73.3
1: FRB 20181030A: ne2001=33.05 != paper 32.3
5: FRB 20220831A: ne2001=1006.04 != paper 989.45
6: FRB 20230521B: ne2001=1179.5 != paper 1174.1
8: FRB 20231220A: ne2001=410.93 != paper 411.3
9: FRB 20240119A: ne2001=415.74 != paper 415.1
10: FRB 20240123A: ne2001=1337.98 != paper 1341.8
12: FRB 20240215A: ne2001=471.21 != paper 471.6
15: FRB 20220207C: ne2001=156.2 != paper 152.98
17: FRB 20220307B: ne2001=340.9 != paper 333.43
18: FRB 20220310F: ne2001=385.81 != paper 386.71
19: FRB 20220330D: ne2001=399.12 != paper 398.75
20: FRB 20220418A: ne2001=556.8 != paper 555.84
21: FRB 20220506D: ne2001=255.35 != paper 277.81
22: FRB 20220509G: ne2001=183.9 != paper 184.29
23: FRB 20220726A: ne2001=572.9 != paper 571.37
24: FRB 20220825A: ne2001=542.74 != paper 541.5
25: FRB 20220914A: ne2001=546.37 != paper 545.86
26: FRB 20220920A: ne2001=245.14 != paper 244.68
27: FRB 20221012A: ne2001=356.85 != paper 357.85
28: FRB 20221027A: ne2001=374.88 != paper 375.36
29: FRB 20221029A: ne2001=1317.9 != paper 1317.42
30: FRB 20221101B: ne2001=338.02 != paper 336.21
31: FRB 20221113A: ne2001=294.72 != paper 293.5
32: FRB 20221116A: ne2001=468.4 != paper 466.8
33: FRB 20221219A: ne2001=632.74 != paper 632.3
34: FRB 20230124A: ne2001=521.44 != paper 521.1
35: FRB 20230216A: ne2001=758.54 != paper 758.8
36: FRB 20230307A: ne2001=541.46 != paper 550.65
37: FRB 20230501A: ne2001=383.92 != paper 383.0
38: FRB 20230626A: ne2001=291.19 != paper 381.9
39: FRB 20230628A: ne2001=275.36 != paper 276.35
40: FRB 20230712A: ne2001=519.13 != paper 518.21
41: FRB 20231120A: ne2001=365.68 != paper 365.8
42: FRB 20231123B: ne2001=326.5 != paper 326.1
43: FRB 20121102A: ne2001=338.58 != paper 339.0
44: FRB 20171020A: ne2001=45.73 != paper 46.1
45: FRB 20180301A: ne2001=341.27 != paper 340.0
46: FRB 20180916B: ne2001=120.39 != paper 119.3
48: FRB 20181112A: ne2001=517.55 != paper 457.27
49: FRB 20181220A: ne2001=53.55 != paper 53.4
51: FRB 20190102C: ne2001=276.2 != paper 276.3
53: FRB 20190303A: ne2001=162.73 != paper 163.4
54: FRB 20190418A: ne2001=84.39 != paper 83.5
55: FRB 20190425A: ne2001=49.4 != paper 49.2
56: FRB 20190520B: ne2001=1114.49 != paper 1061.7
57: FRB 20190523A: ne2001=693.62 != paper 693.8
60: FRB 20190614D: ne2001=841.2 != paper 845.7
62: FRB 20190714A: ne2001=435.51 != paper 435.0
63: FRB 20191001A: ne2001=432.75 != paper 432.22
67: FRB 20200430A: ne2001=322.92 != paper 323.1
68: FRB 20200906A: ne2001=511.96 != paper 511.8
69: FRB 20201123A: ne2001=151.89 != paper 151.62
70: FRB 20201124A: ne2001=243.39 != paper 260.32
72: FRB 20210320C: ne2001=315.51 != paper 312.8
73: FRB 20210405I: ne2001=18.39 != paper 19.07
75: FRB 20210603A: ne2001=430.61 != paper 430.15
78: FRB 20211203C: ne2001=542.47 != paper 543.2
79: FRB 20211212A: ne2001=137.25 != paper 148.9
81: FRB 20220319D: ne2001=-58.76 != paper 15.7
82: FRB 20220501C: ne2001=388.88 != paper 388.5
84: FRB 20220725A: ne2001=229.67 != paper 229.4
85: FRB 20220912A: ne2001=588.74 != paper 64.46
86: FRB 20220918A: ne2001=586.06 != paper 585.8
87: FRB 20221106A: ne2001=250.2 != paper 278.8
88: FRB 20230526A: ne2001=299.54 != paper 281.4
89: FRB 20230708A: ne2001=321.18 != paper 331.51
90: FRB 20230718A: ne2001=25.95 != paper 53.6
91: FRB 20230902A: ne2001=375.96 != paper 376.1
92: FRB 20231226A: ne2001=261.81 != paper 154.9
93: FRB 20240114A: ne2001=448.28 != paper 457.7
94: FRB 20240201A: ne2001=305.88 != paper 306.5
95: FRB 20240210A: ne2001=225.11 != paper 222.73
96: FRB 20240310A: ne2001=541.7 != paper 535.8
97: FRB 20200120E: ne2001=17.15 != paper 17.74
98: FRB 20230203A: ne2001=353.84 != paper 354.81
99: FRB 20230222A: ne2001=541.9 != paper 556.03
100: FRB 20230222B: ne2001=130.07 != paper 130.18
101: FRB 20230311A: ne2001=241.84 != paper 248.31
102: FRB 20230703A: ne2001=234.37 != paper 234.6
103: FRB 20230730A: ne2001=197.34 != paper 201.92
104: FRB 20230926A: ne2001=140.18 != paper 139.28
105: FRB 20231005A: ne2001=125.93 != paper 125.08
106: FRB 20231011A: ne2001=85.95 != paper 87.08
107: FRB 20231017A: ne2001=249.65 != paper 249.31
108: FRB 20231025B: ne2001=290.11 != paper 289.45
109: FRB 20231123A: ne2001=182.35 != paper 186.69
110: FRB 20231128A: ne2001=276.59 != paper 271.27
111: FRB 20231201A: ne2001=69.45 != paper 71.94
112: FRB 20231204A: ne2001=161.17 != paper 159.94
113: FRB 20231206A: ne2001=368.56 != paper 370.12
114: FRB 20231223C: ne2001=87.93 != paper 87.07
115: FRB 20231229A: ne2001=110.32 != paper 110.98
116: FRB 20231230A: ne2001=39.82 != paper 41.02

In [7]:
""" plt.figure(figsize=(14, 8))
fs=6
sns.stripplot(x=data['FRB'], y=data['DM_ext(ne2001)'], size=1, jitter=False, 
              palette='viridis', edgecolor='black', linewidth=1)
plt.title('FRB Redshift Distribution (Seaborn)', fontsize=fs+2)
plt.xlabel('FRB Name', fontsize=fs)
plt.ylabel('Redshift (z)', fontsize=fs)
plt.xticks(rotation=45, ha='right',fontsize=fs)
plt.yticks(fontsize=fs)
plt.grid(axis='y', linestyle='--', alpha=0.7) """

" plt.figure(figsize=(14, 8))\nfs=6\nsns.stripplot(x=data['FRB'], y=data['DM_ext(ne2001)'], size=1, jitter=False, \n              palette='viridis', edgecolor='black', linewidth=1)\nplt.title('FRB Redshift Distribution (Seaborn)', fontsize=fs+2)\nplt.xlabel('FRB Name', fontsize=fs)\nplt.ylabel('Redshift (z)', fontsize=fs)\nplt.xticks(rotation=45, ha='right',fontsize=fs)\nplt.yticks(fontsize=fs)\nplt.grid(axis='y', linestyle='--', alpha=0.7) "

In [8]:
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x,73.07,52.49
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...,33.05,41.15
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,176.05,185.08
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...,1397.19,1414.57
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,489.01,524.12

In [9]:
data=data[['FRB', 'z', 'gl', 'gb', 'DM', 'DM_ext(ne2001)', 'DM_ext(ymw16)', 'Ref.']]
data.head()

,FRB,z,gl,gb,DM,DM_ext(ne2001),DM_ext(ymw16),Ref.
0,FRB 20180814A,0.06800,136.460000,16.580000,190.900,73.07,52.49,https://www.nature.com/articles/s41586-018-0864-x
1,FRB 20181030A,0.00385,133.400000,40.900000,103.396,33.05,41.15,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20220529A,0.18390,130.787670,-41.858020,246.000,176.05,185.08,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01600,8.839200,-70.185700,1458.150,1397.19,1414.57,https://www.cambridge.org/core/journals/public...
4,FRB 20220717A,0.36295,19.835158,-17.632032,637.340,489.01,524.12,https://arxiv.org/pdf/2407.02173

In [10]:
data.to_csv("../../Data/FRB_new.csv",index=None)