Recalculate all $DM_{MW,ISM}$ based on our (gl, gb) and pygedm (see `ne2001_compare.ipynb`)

In [1]:
import sys
sys.path.append('../../Python_scripts')

## Import packages
from config import *
from support import *
from cosmo_support import *
import seaborn as sns

import pygedm

/home/zhuge/miniconda3/lib/python3.10/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

load data

In [2]:
data=pd.read_csv('../../Data/FRB.csv')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173

In [3]:
cosmo = Planck18

In [4]:
for idx in range(len(data)):
    dis=cosmo.luminosity_distance(data['z'].iloc[idx])/u.Mpc
    data.loc[idx,'DM_MW, ISM(NE2001)'] = pygedm.dist_to_dm(gl=data['gl'].iloc[idx], 
                            gb=data['gb'].iloc[idx], 
                            dist=dis.value*1e6, 
                            method='ne2001')[0].value
    data.loc[idx,'DM_MW, ISM(YMW16)'] = pygedm.dist_to_dm(gl=data['gl'].iloc[idx], 
                            gb=data['gb'].iloc[idx], 
                            dist=dis.value*1e6, 
                            method='ymw16')[0].value
data.head()

/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)
/home/zhuge/miniconda3/lib/python3.10/site-packages/pygedm/pygedm.py:112: UserWarning: Distance too large, setting to 50 kpc.
  warnings.warn("Distance too large, setting to 50 kpc.", UserWarning)

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)"
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x,87.826096,108.406677
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...,40.350502,32.243271
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.951168,30.923595
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...,30.957880,13.578911
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.331604,83.223785

In [5]:
DM_MW_halo=30
data['DM_ext(ne2001)'] = data['DM']-DM_MW_halo-data['DM_MW, ISM(NE2001)'] #apply(lambda x: f'{x:.2f}')
data['DM_ext(ymw16)'] = data['DM']-DM_MW_halo-data['DM_MW, ISM(YMW16)'] #.apply(lambda x: f'{x:.2f}')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x,87.826096,108.406677,73.073904,52.493323
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...,40.350502,32.243271,33.045498,41.152729
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.951168,30.923595,176.048832,185.076405
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...,30.957880,13.578911,1397.192120,1414.571089
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.331604,83.223785,489.008396,524.116215

In [6]:
data['DM_MW, ISM(NE2001)'] = data['DM_MW, ISM(NE2001)'].round(2) #apply(lambda x: f'{x:.2f}')
data['DM_MW, ISM(YMW16)'] = data['DM_MW, ISM(YMW16)'].round(2) #.apply(lambda x: f'{x:.2f}')
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x,87.83,108.41,73.073904,52.493323
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...,40.35,32.24,33.045498,41.152729
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.95,30.92,176.048832,185.076405
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...,30.96,13.58,1397.192120,1414.571089
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.33,83.22,489.008396,524.116215

In [7]:
for idx in range(len(data)):
    if np.abs(data['DM_ext(ne2001)'].iloc[idx] - data['DM_ext'].iloc[idx]) > 0.1:
        print(f"{idx}: {data['FRB'].iloc[idx]}: ne2001={data['DM_ext(ne2001)'].iloc[idx]} != paper {data['DM_ext'].iloc[idx]}")

0: FRB 20180814A: ne2001=73.07390441894532 != paper 73.3
1: FRB 20181030A: ne2001=33.045497985839845 != paper 32.3
5: FRB 20220831A: ne2001=1006.0371780395508 != paper 989.45
6: FRB 20230521B: ne2001=1179.5019439697267 != paper 1174.1
8: FRB 20231220A: ne2001=410.9344856262207 != paper 411.3
9: FRB 20240119A: ne2001=415.7366081237793 != paper 415.1
10: FRB 20240123A: ne2001=1337.9801864624023 != paper 1341.8
12: FRB 20240215A: ne2001=471.20966720581055 != paper 471.6
15: FRB 20220207C: ne2001=156.20245819091798 != paper 152.98
17: FRB 20220307B: ne2001=340.90370788574216 != paper 333.43
18: FRB 20220310F: ne2001=385.81288757324216 != paper 386.71
19: FRB 20220330D: ne2001=399.1211563110352 != paper 398.75
20: FRB 20220418A: ne2001=556.7978546142579 != paper 555.84
21: FRB 20220506D: ne2001=255.35381286621094 != paper 277.81
22: FRB 20220509G: ne2001=183.90061569213867 != paper 184.29
23: FRB 20220726A: ne2001=572.9042251586914 != paper 571.37
24: FRB 20220825A: ne2001=542.7408630371094 != paper 541.5
25: FRB 20220914A: ne2001=546.3669288635253 != paper 545.86
26: FRB 20220920A: ne2001=245.13671112060547 != paper 244.68
27: FRB 20221012A: ne2001=356.85362548828124 != paper 357.85
28: FRB 20221027A: ne2001=374.8814125061035 != paper 375.36
29: FRB 20221029A: ne2001=1317.899006652832 != paper 1317.42
30: FRB 20221101B: ne2001=338.01607818603514 != paper 336.21
31: FRB 20221113A: ne2001=294.71988635253905 != paper 293.5
32: FRB 20221116A: ne2001=468.39950756835935 != paper 466.8
33: FRB 20221219A: ne2001=632.7428625183105 != paper 632.3
34: FRB 20230124A: ne2001=521.4442011108398 != paper 521.1
35: FRB 20230216A: ne2001=758.5358428955078 != paper 758.8
36: FRB 20230307A: ne2001=541.4554480590821 != paper 550.65
37: FRB 20230501A: ne2001=383.9168465576172 != paper 383.0
38: FRB 20230626A: ne2001=291.1878952026367 != paper 381.9
39: FRB 20230628A: ne2001=275.3584254760742 != paper 276.35
40: FRB 20230712A: ne2001=519.1252962036133 != paper 518.21
41: FRB 20231120A: ne2001=365.67819061279295 != paper 365.8
42: FRB 20231123B: ne2001=326.49671328735354 != paper 326.1
43: FRB 20121102A: ne2001=338.57701110839844 != paper 339.0
44: FRB 20171020A: ne2001=45.72812423706054 != paper 46.1
45: FRB 20180301A: ne2001=341.2745361328125 != paper 340.0
46: FRB 20180916B: ne2001=120.39283447265626 != paper 119.3
48: FRB 20181112A: ne2001=517.5504145812988 != paper 457.27
49: FRB 20181220A: ne2001=53.551550292968756 != paper 53.4
53: FRB 20190303A: ne2001=162.73424758911133 != paper 163.4
54: FRB 20190418A: ne2001=84.38522338867188 != paper 83.5
55: FRB 20190425A: ne2001=49.40499038696288 != paper 49.2
56: FRB 20190520B: ne2001=1114.4934913635254 != paper 1061.7
57: FRB 20190523A: ne2001=693.6202590942382 != paper 693.8
60: FRB 20190614D: ne2001=841.2002517700196 != paper 845.7
62: FRB 20190714A: ne2001=435.50876235961914 != paper 435.0
63: FRB 20191001A: ne2001=432.74581329345705 != paper 432.22
67: FRB 20200430A: ne2001=322.91762886047366 != paper 323.1
68: FRB 20200906A: ne2001=511.96366577148433 != paper 511.8
69: FRB 20201123A: ne2001=151.8935974121094 != paper 151.62
70: FRB 20201124A: ne2001=243.3883166503906 != paper 260.32
72: FRB 20210320C: ne2001=315.5119369506836 != paper 312.8
73: FRB 20210405I: ne2001=18.38789550781246 != paper 19.07
75: FRB 20210603A: ne2001=430.61314837646484 != paper 430.15
78: FRB 20211203C: ne2001=542.4724647521973 != paper 543.2
79: FRB 20211212A: ne2001=137.24811553955078 != paper 148.9
81: FRB 20220319D: ne2001=-58.7599609375 != paper 15.7
82: FRB 20220501C: ne2001=388.8774948120117 != paper 388.5
84: FRB 20220725A: ne2001=229.66797866821287 != paper 229.4
85: FRB 20220912A: ne2001=588.7400534057617 != paper 64.46
86: FRB 20220918A: ne2001=586.0567634582519 != paper 585.8
87: FRB 20221106A: ne2001=250.2003958129883 != paper 278.8
88: FRB 20230526A: ne2001=299.5401271820068 != paper 281.4
89: FRB 20230708A: ne2001=321.18367935180663 != paper 331.51
90: FRB 20230718A: ne2001=25.951287841796898 != paper 53.6
91: FRB 20230902A: ne2001=375.9648567199707 != paper 376.1
92: FRB 20231226A: ne2001=261.8089660644531 != paper 154.9
93: FRB 20240114A: ne2001=448.2836982727051 != paper 457.7
94: FRB 20240201A: ne2001=305.8835029602051 != paper 306.5
95: FRB 20240210A: ne2001=225.10719375610353 != paper 222.73
96: FRB 20240310A: ne2001=541.6990516662597 != paper 535.8
97: FRB 20200120E: ne2001=17.150959320068353 != paper 17.74
98: FRB 20230203A: ne2001=353.83727798461916 != paper 354.81
99: FRB 20230222A: ne2001=541.9014831542969 != paper 556.03
100: FRB 20230222B: ne2001=130.06698875427247 != paper 130.18
101: FRB 20230311A: ne2001=241.84404449462892 != paper 248.31
102: FRB 20230703A: ne2001=234.372416305542 != paper 234.6
103: FRB 20230730A: ne2001=197.3438491821289 != paper 201.92
104: FRB 20230926A: ne2001=140.18003158569337 != paper 139.28
105: FRB 20231005A: ne2001=125.92962493896485 != paper 125.08
106: FRB 20231011A: ne2001=85.94981079101564 != paper 87.08
107: FRB 20231017A: ne2001=249.64934844970702 != paper 249.31
108: FRB 20231025B: ne2001=290.11133499145507 != paper 289.45
109: FRB 20231123A: ne2001=182.35138092041018 != paper 186.69
110: FRB 20231128A: ne2001=276.5937152862549 != paper 271.27
111: FRB 20231201A: ne2001=69.44795837402344 != paper 71.94
112: FRB 20231204A: ne2001=161.17134475708008 != paper 159.94
113: FRB 20231206A: ne2001=368.5641319274902 != paper 370.12
114: FRB 20231223C: ne2001=87.93407516479493 != paper 87.07
115: FRB 20231229A: ne2001=110.31969833374023 != paper 110.98
116: FRB 20231230A: ne2001=39.82437362670899 != paper 41.02

In [8]:
""" plt.figure(figsize=(14, 8))
fs=6
sns.stripplot(x=data['FRB'], y=data['DM_ext(ne2001)'], size=1, jitter=False, 
              palette='viridis', edgecolor='black', linewidth=1)
plt.title('FRB Redshift Distribution (Seaborn)', fontsize=fs+2)
plt.xlabel('FRB Name', fontsize=fs)
plt.ylabel('Redshift (z)', fontsize=fs)
plt.xticks(rotation=45, ha='right',fontsize=fs)
plt.yticks(fontsize=fs)
plt.grid(axis='y', linestyle='--', alpha=0.7) """

" plt.figure(figsize=(14, 8))\nfs=6\nsns.stripplot(x=data['FRB'], y=data['DM_ext(ne2001)'], size=1, jitter=False, \n              palette='viridis', edgecolor='black', linewidth=1)\nplt.title('FRB Redshift Distribution (Seaborn)', fontsize=fs+2)\nplt.xlabel('FRB Name', fontsize=fs)\nplt.ylabel('Redshift (z)', fontsize=fs)\nplt.xticks(rotation=45, ha='right',fontsize=fs)\nplt.yticks(fontsize=fs)\nplt.grid(axis='y', linestyle='--', alpha=0.7) "

In [9]:
data.head()

,FRB,z,DM,DM_ext,gl,gb,From,Ref,Ref.,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16)
0,FRB 20180814A,0.06800,190.900,73.30,136.460000,16.580000,Fan,https://www.nature.com/articles/s41586-018-0864-x,https://www.nature.com/articles/s41586-018-0864-x,87.83,108.41,73.073904,52.493323
1,FRB 20181030A,0.00385,103.396,32.30,133.400000,40.900000,Fan,https://iopscience.iop.org/article/10.3847/204...,https://iopscience.iop.org/article/10.3847/204...,40.35,32.24,33.045498,41.152729
2,FRB 20220529A,0.18390,246.000,176.00,130.787670,-41.858020,Fan,https://arxiv.org/abs/2503.04727,https://arxiv.org/abs/2503.04727,39.95,30.92,176.048832,185.076405
3,FRB 20220610A,1.01600,1458.150,1397.15,8.839200,-70.185700,Fan,https://www.cambridge.org/core/journals/public...,https://www.cambridge.org/core/journals/public...,30.96,13.58,1397.192120,1414.571089
4,FRB 20220717A,0.36295,637.340,489.04,19.835158,-17.632032,Fan,https://arxiv.org/pdf/2407.02173,https://arxiv.org/pdf/2407.02173,118.33,83.22,489.008396,524.116215

In [10]:
data=data[['FRB', 'z', 'gl', 'gb', 'DM', 'DM_MW, ISM(NE2001)', 'DM_MW, ISM(YMW16)', 'DM_ext(ne2001)', 'DM_ext(ymw16)', 'Ref.']]
data.head()

,FRB,z,gl,gb,DM,"DM_MW, ISM(NE2001)","DM_MW, ISM(YMW16)",DM_ext(ne2001),DM_ext(ymw16),Ref.
0,FRB 20180814A,0.06800,136.460000,16.580000,190.900,87.83,108.41,73.073904,52.493323,https://www.nature.com/articles/s41586-018-0864-x
1,FRB 20181030A,0.00385,133.400000,40.900000,103.396,40.35,32.24,33.045498,41.152729,https://iopscience.iop.org/article/10.3847/204...
2,FRB 20220529A,0.18390,130.787670,-41.858020,246.000,39.95,30.92,176.048832,185.076405,https://arxiv.org/abs/2503.04727
3,FRB 20220610A,1.01600,8.839200,-70.185700,1458.150,30.96,13.58,1397.192120,1414.571089,https://www.cambridge.org/core/journals/public...
4,FRB 20220717A,0.36295,19.835158,-17.632032,637.340,118.33,83.22,489.008396,524.116215,https://arxiv.org/pdf/2407.02173

In [11]:
data.to_csv("../../Data/FRB_new.csv",index=None)